# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_listview.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import compute
from datetime import datetime
from skyfield.api import utc
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 160, 500))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.itemClicked.connect(self.selectedList)

        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(235, 20, 75, 25))
        self.testButton.setObjectName("testButton")
        self.testButton.clicked.connect(self.test)

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 20, 210, 25))
        self.label1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label1.setText("")
        self.label1.setObjectName("label1")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.testButton.setText(_translate("MainWindow", "Test"))

    def test(self):
        lat = '7.83305556 S'
        long = '110.38305556 E'
        t0 = datetime(2021, 1, 6, tzinfo=utc)
        t1 = datetime(2021, 5, 6, tzinfo=utc)
        compute.result(lat, long, t0, t1)
        data = compute.var.df
        sunset = data['Waktu Sunset (UTC+07)'].tolist()
        sunset = [str(i) for i in sunset]
        self.listWidget.addItems(sunset)

    def selectedList(self):
        row = self.listWidget.currentRow()
        print(row)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())