# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, QTime, QDateTime, QAbstractTableModel, Qt
import compute

import matplotlib
matplotlib.use('Qt5Agg')

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 700)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 171))
        self.groupBox.setObjectName("groupBox")

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 50, 20))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 50, 20))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 50, 20))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 50, 20))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 50, 20))
        self.label_5.setObjectName("label_5")

        # Tombol Hitung
        self.button_hitung = QtWidgets.QPushButton(self.groupBox)
        self.button_hitung.setGeometry(QtCore.QRect(100, 130, 70, 30))
        self.button_hitung.setObjectName("button_hitung")
        self.button_hitung.clicked.connect(self.Hitung)

        # Latitude
        self.latitude = QtWidgets.QLineEdit(self.groupBox)
        self.latitude.setGeometry(QtCore.QRect(70, 20, 100, 20))
        self.latitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.latitude.setObjectName("latitude")
        self.latitude.setText('7.83305556 S')
        print('Latitude:', self.latitude.text())

        # Longitude
        self.longitude = QtWidgets.QLineEdit(self.groupBox)
        self.longitude.setGeometry(QtCore.QRect(70, 40, 100, 20))
        self.longitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.longitude.setObjectName("longitude")
        self.longitude.setText('110.38305556 E')
        print('Longitude:', self.longitude.text())

        # Waktu t0
        t0 = QtCore.QDate.currentDate()
        self.dateEdit_1 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_1.setGeometry(QtCore.QRect(70, 60, 100, 20))
        self.dateEdit_1.setObjectName("dateEdit_1")
        self.dateEdit_1.setDate(t0)
        print('t0:', t0.toPyDate())

        # Waktu t1
        t1 = t0.addMonths(1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(70, 80, 100, 20))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setDate(t1)
        print('t1:', t1.toPyDate())

        self.horizon = QtWidgets.QLineEdit(self.groupBox)
        self.horizon.setGeometry(QtCore.QRect(70, 100, 100, 20))
        self.horizon.setObjectName("horizon")

        # Tabel 1
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(200, 20, 1140, 311))
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSortingEnabled(True)
        self.tableView.setWordWrap(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)

        # Tombol Simpan
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1150, 340, 70, 30))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 370, 471, 281))
        self.groupBox_2.setObjectName("groupBox_2")

        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(10, 20, 42, 22))
        self.spinBox.setObjectName("spinBox")

        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 30, 20))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 30, 20))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 60, 20))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 80, 20))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 80, 20))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 90, 20))
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 90, 20))
        self.label_13.setObjectName("label_13")

        self.tableView_2 = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_2.setGeometry(QtCore.QRect(10, 70, 150, 200))
        self.tableView_2.setObjectName("tableView_2")

        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(170, 30, 290, 240))
        self.graphicsView.setObjectName("graphicsView")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 20))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hilal"))
        self.groupBox.setTitle(_translate("MainWindow", "Parameter"))
        self.label.setText(_translate("MainWindow", "Latitude"))
        self.label_2.setText(_translate("MainWindow", "Longitude"))
        self.label_3.setText(_translate("MainWindow", "Dari"))
        self.label_4.setText(_translate("MainWindow", "Sampai"))
        self.label_5.setText(_translate("MainWindow", "Horizon"))
        self.button_hitung.setText(_translate("MainWindow", "Hitung"))
        self.pushButton.setText(_translate("MainWindow", "Simpan"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_6.setText(_translate("MainWindow", "Dari"))
        self.label_7.setText(_translate("MainWindow", "00"))
        self.label_8.setText(_translate("MainWindow", "Konjungsi"))
        self.label_9.setText(_translate("MainWindow", "Hilal"))
        self.label_10.setText(_translate("MainWindow", "Altitude Bulan"))
        self.label_11.setText(_translate("MainWindow", "Azimuth Bulan"))
        self.label_12.setText(_translate("MainWindow", "Altitude Matahari"))
        self.label_13.setText(_translate("MainWindow", "Azimuth Matahari"))

    def Hitung(self):
        lat = self.latitude.text()
        long = self.longitude.text()
        t0 = self.dateEdit_1.date().toPyDate()
        t1 = self.dateEdit_2.date().toPyDate()
        print()
        print(lat)
        print(long)
        print(type(t0))
        print(type(t1))

        compute.result(lat, long, t0, t1)
        model = pandasModel(compute.var.df)
        self.tableView.setModel(model)
        self.tableView.resizeColumnsToContents()

class pandasModel(QAbstractTableModel):

    def __init__(self, data):
        QAbstractTableModel.__init__(self)
        self._data = data

    def rowCount(self, parent=None):
        return self._data.shape[0]

    def columnCount(self, parnet=None):
        return self._data.shape[1]
        # return 1

    def data(self, index, role=Qt.DisplayRole):
        if index.isValid():
            if role == Qt.DisplayRole:
                return str(self._data.iloc[index.row(), index.column()])
        return None

    def headerData(self, col, orientation, role):
        if orientation == Qt.Horizontal and role == Qt.DisplayRole:
            return self._data.columns[col]
        return None


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
